chat/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from chat.views.collectivity_discussions_view import (
    CollectivityDiscussionsView
)
from chat.views.create_comment_view import CreateCommentView
from chat.views.create_discussion_view import CreateDiscussionView
from chat.views.read_discussion_view import ReadDiscussionView


app_name = 'chat'

urlpatterns = [
    path(
        'collectivity_discussions/',
        CollectivityDiscussionsView.as_view(),
        name='collectivity_discussions'
    ),
    path(
        'create_comment/<int:id_discussion>/',
        CreateCommentView.as_view(),
        name='create_comment'
    ),
    path(
        'create_discussion/',
        CreateDiscussionView.as_view(),
        name='create_discussion'
    ),
    path(
        'read_discussion/<int:id_discussion>/',
        ReadDiscussionView.as_view(),
        name='read_discussion'
    )
]

vote/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from vote.views.collectivity_votings_view import CollectivityVotingsView
from vote.views.create_vote_view import CreateVoteView
from vote.views.create_voting_view import CreateVotingView
from vote.views.delete_voting_view import DeleteVotingView
from vote.views.read_voting_view import ReadVotingView


app_name = 'vote'

urlpatterns = [
    path(
        'collectivity_votings/',
        CollectivityVotingsView.as_view(),
        name='collectivity_votings'
    ),
    path(
        'create_vote/<int:id_voting>/',
        CreateVoteView.as_view(),
        name='create_vote'
    ),
    path('create_voting/', CreateVotingView.as_view(), name='create_voting'),
    path(
        'delete_voting/<int:id_voting>/',
        DeleteVotingView.as_view(),
        name='delete_voting'
    ),
    path(
        'read_voting/<int:id_voting>/',
        ReadVotingView.as_view(),
        name='read_voting'
    ),
]

vote/forms/add_voting.py
"""Add voting form
"""
from datetime import date
from django.forms import (
    CharField, DateField, DateInput, IntegerField, ModelForm, Select, Textarea,
    TextInput, 
)

from vote.management.engine.manager import Manager
from vote.models.voting import Voting
from vote.models.voting_method import VotingMethod


class AddVoting(ModelForm):
    """Add voting form class. Used for adding voting.
    """
    question = CharField(
        label='Question',
        max_length=256,
        widget=TextInput(
            attrs={
                'class': 'form-control form-control-sm',
                'id': 'input_voting_question'
            }
        )
    )
    description = CharField(
        label='Description',
        max_length=1000,
        widget=Textarea(
            attrs={
                'class': 'form-control form-control-sm',
                'id': 'input_voting_description',
                'rows':4
            }
        )
    )
    opening_date = DateField(
        label='Date d\'ouverture du vote',
        widget=DateInput(
            attrs={
                'type': 'date',
                'class': 'input-group date form-control form-control-sm',
                'data-target-input': "nearest",
                'id': 'input_voting_opening_date',
            }
        )
    )
    voting_method = IntegerField(
        label='Mode de scrutin',
        widget=Select(
            attrs={
                'class': 'form-control form-control-sm',
                'id': 'input_voting_voting_method',
            },
            choices=VotingMethod.objects.values_list('id', 'name')
        )
    )

    class Meta:
        model = Voting
        fields = (
            'question', 'description', 'opening_date',
            # 'opening_date',
            # 'closure_date',
        )
    

        # widgets = {
        #     'question': forms.CharField(
        #         attrs={
        #             'id': 'inputVotingQuestion',
        #             'class': 'form-control form-control-sm' 
        #         },
        #     )
        # }
    # choices_list = [
    #     (None, ""),
    #     (1, "Très mauvais (une étoile)"),
    #     (2, "Mauvais (deux étoiles)"),
    #     (3, "Moyen (trois étoiles)"),
    #     (4, "Bon (quatre étoiles)"),
    #     (5, "Très bon (cinq étoiles)")
    # ]
    # ratings = forms.IntegerField(
    #     label="Note le produit:",
    #     widget=forms.Select(
    #         attrs={
    #             'class': 'form-control',
    #             'id': 'rating_form_attr'
    #         },
    #         choices=choices_list,
    #     )
    # )

vote/forms/collectivity_votings_form.py
"""Collectivity Voting Form module.
"""
from django.forms import CharField, Form, TextInput


class CollectivityVotingsForm(Form):
    """CollectivityVotingsForm class.
    """

    search_input = CharField(
        label='Rechercher',
        max_length=256,
        widget=TextInput(
            attrs={
                'id': 'input_search_votings',
                'class': 'form-control form-control-sm',
                'autofocus': False,
            }
        )
    )

vote/views/add_voting.py
"""AddVoting view module
"""
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import View
from django.shortcuts import render
from django.urls import reverse

from vote.forms.voting_form import VotingForm
from vote.management.engine.manager import Manager


class AddVoting(View):
    """AddVoting view class.
    """

    def __init__(self):
        super().__init__()
        self.context = {
            'voting_form': VotingForm(),
        }
        self.get_success_template = 'vote/add_voting.html'
        self.post_success_template = 'vote:overview'
        self.post_fail_template = 'vote:add_voting'

    def get(self, request):
        """Voting page view method on user get request.
        """
        return render(request, self.get_success_template, self.context)
    
    def post(self, request):
        """Voting page view method on client post request. Create voting
        into the DB. After Voting creation, user is redirect to voting 
        overview page.
        """
        form = VotingForm(request.POST)
        if form.is_valid():
            Manager().create_voting(form)
            return HttpResponseRedirect(reverse(self.post_success_template))
        else:
            messages.add_message(
                request, messages.ERROR, (
                    "Une ou plusieurs informations a été incorrectement"
                    "saisie Veuiller ressaisir le information!"
                )
            )
            return HttpResponseRedirect(reverse(self.post_fail_template))

vote/views/collectivity_votings_view.py
"""CollectivityVotingsView module.
"""
from django.shortcuts import render

from vote.forms.collectivity_votings_form import CollectivityVotingsForm
from vote.views.generic_vote_view import GenericVoteView


class CollectivityVotingsView(GenericVoteView):
    """CollectivityVotingsView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'vote/votings.html'
        self.context = {
            'form': CollectivityVotingsForm(),
            'page_objects': None,
        }

    def get(self, request):
        """CollectivityVotingsView method on client get request.
        """
        search_input = request.session.get('c_v_v_f_search_input', None)
        if search_input:
            self.context['page_objects'] = (
                self.manager.set_page_objects_context(request, search_input)
            )
            return render(request, self.view_template, self.context)
        self.context['page_objects'] = (
            self.manager.set_page_objects_context(request, False)
        )
        return render(request, self.view_template, self.context)

    def post(self, request):
        """CollectivityVotingsView method on client post request.
        """
        if request.POST.get('cvf_search_button') == 'yes':
            form = CollectivityVotingsForm(request.POST)
            if form.is_valid():
                search_input = form.cleaned_data['search_input']
                self.context['page_objects'] = (
                    self.manager.set_page_objects_context(
                        request, search_input
                    )
                )
                self.manager.set_session_vars(request, search_input)
            else:
                self.context['form'] = form
                self.context['page_objects'] = (
                    self.manager.set_page_objects_context(request, False)
                )
        else:
            self.context['page_objects'] = (
                self.manager.set_page_objects_context(request, False)
            )
            self.manager.set_session_vars(request, False)
        return render(request, self.view_template, self.context)

vote/views/create_vote_view.py
# pylint: disable=E1101
"""CreateVoteView module.
"""
from django.contrib import messages
from django.shortcuts import redirect, render

from vote.models import Vote, Voting
from vote.views.generic_vote_view import GenericVoteView


class CreateVoteView(GenericVoteView):
    """CreateVoteView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'vote/create_vote.html'
        self.alternative_one_view_name = 'vote:read_voting'
        self.context = {
            'voting': None,
        }
        self.msg_already_voted = "Vous avez déja voté"
        self.msg_post_success = "A voté!"

    def get(self, request, id_voting):
        """CreateVoteView method on client get request.
        """
        voting = Voting.objects.get(pk=id_voting)
        vote = Vote.objects.filter(
            vote_voting__exact=id_voting,
            vote_custom_user__exact=request.user.id
        )
        if len(vote) == 0:
            self.context['voting'] = voting
            return render(request, self.view_template, self.context)
        messages.add_message(
            request, messages.ERROR, self.msg_already_voted
        )
        return redirect(self.alternative_one_view_name, id_voting)

    def post(self, request, id_voting):
        """CreateVoteView method on client post request.
        """
        vote = Vote.objects.filter(
            vote_voting__exact=id_voting,
            vote_custom_user__exact=request.user.id
        )
        if len(vote) == 0:
            self.manager.create_vote(request, id_voting)
            messages.add_message(
                request, messages.SUCCESS, self.msg_post_success
            )
            return redirect(self.alternative_one_view_name, id_voting)
        messages.add_message(
            request, messages.ERROR, self.msg_already_voted
        )
        return redirect(self.alternative_one_view_name, id_voting)

vote/views/create_voting_view.py
"""CreateVotingView module.
"""
from django.contrib import messages
from django.shortcuts import redirect, render

from vote.forms.voting_form import VotingForm
from vote.views.generic_vote_view import GenericVoteView


class CreateVotingView(GenericVoteView):
    """CreateVotingView class.
    """

    def __init__(self):
        super().__init__()
        self.context = {
            'form': VotingForm(),
        }
        self.view_template = 'vote/create_voting.html'
        self.alternative_view_name = 'information:home'
        self.post_view_name = 'vote:collectivity_votings'

    def get(self, request):
        """CreateVotingView method on user get request.
        """
        return render(request, self.view_template, self.context)

    def post(self, request):
        """CreateVotingView method on client post request.
        """
        form = VotingForm(request.POST)
        if form.is_valid():
            self.manager.create_voting(form, request.user)
            messages.add_message(
                request, messages.SUCCESS, "Création réussie",
            )
            return redirect(self.post_view_name)
        self.context['form'] = form
        return render(request, self.view_template, self.context)

vote/views/delete_voting_view.py
# pylint: disable=E1101
"""DeleteVotingView module.
"""
from django.contrib import messages
from django.shortcuts import redirect, render

from vote.models import Voting
from vote.views.generic_vote_view import GenericVoteView


class DeleteVotingView(GenericVoteView):
    """DeleteVotingView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'vote/delete_voting.html'
        self.alternative_one_view_name = 'vote:collectivity_votings'
        self.context = {
            'voting': None
        }
        self.msg_unauthenticated = "Authentification requise"
        self.msg_not_owner = (
            "Le créateur seulement peut supprimer la votation"
        )
        self.msg_post_success = "Suppression de votation réussie"

    def get(self, request, id_voting):
        """DeleteVotingView method on client get request.
        """
        voting = Voting.objects.get(pk=id_voting)
        if voting.voting_custom_user_id == request.user.id:
            self.context['voting'] = voting
            return render(request, self.view_template, self.context)
        messages.add_message(
            request, messages.ERROR, self.msg_not_owner,
        )
        return redirect(self.alternative_one_view_name)

    def post(self, request, id_voting):
        """DeleteVotingView method on client post request.
        """
        voting = Voting.objects.get(pk=id_voting)
        if voting.voting_custom_user_id == request.user.id:
            voting.delete()
            messages.add_message(
                request, messages.SUCCESS, self.msg_post_success
            )
            return redirect(self.alternative_one_view_name)
        messages.add_message(
            request, messages.ERROR, self.msg_not_owner
        )
        return redirect(self.alternative_one_view_name)

vote/views/detailed_voting_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.shortcuts import render

from vote.management.engine.manager import Manager
from vote.models.voting import Voting


class DetailedVotingView(LoginRequiredMixin, View):
    """DetailedVotingView class.
    """
    login_url = '/authentication/login/'
    redirect_field_name = None

    def __init__(self):
        super().__init__()
        self.manager = Manager()
        self.view_template = 'vote/detailed_voting.html'
        self.context = {
            'voting': None,
            'voting_operation': None, 
            'voting_result': None,                       
            'voting_status': None
        }
        self.msg_unauthenticated = "Authentification requise"
    
    def get(self, request, id_voting):
        """Detailed voting view method on client get request.
        """
        voting = Voting.objects.get(pk=id_voting)
        self.context = self.manager.set_context(
            self.context, voting, 'read'
        )
        return render(request, self.view_template, self.context)

vote/views/generic_vote_view.py
"""GenericVoteView module.
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from vote.management.engine.manager import Manager


class GenericVoteView(LoginRequiredMixin, View):
    """GenericVoteView class.
    """

    login_url = '/authentication/login/'
    redirect_field_name = None

    def __init__(self):
        super().__init__()
        self.manager = Manager()

vote/views/read_voting_view.py
# pylint: disable=E1101
"""ReadVotingView module.
"""
from django.shortcuts import render

from vote.models import Voting
from vote.views.generic_vote_view import GenericVoteView


class ReadVotingView(GenericVoteView):
    """ReadVotingView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'vote/read_voting.html'
        self.context = {
            'voting': None,
            'voting_operation': None,
            'voting_result': None,
            'voting_status': None
        }
        self.msg_unauthenticated = "Authentification requise"

    def get(self, request, id_voting):
        """Detailed voting view method on client get request.
        """
        voting = Voting.objects.get(pk=id_voting)
        self.context = self.manager.set_context(
            self.context, voting, 'read'
        )
        return render(request, self.view_template, self.context)

vote/templates/vote/create_vote.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class=" login-page">
    <div class="login-box ">
        <div class="login-logo">
            <a href="../../index2.html"><b>sel-</b>E</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Participer au vote</p>
                <p class="font-weight-bold"> "{{voting.question}}"</p>
                <form id="create_vote_form" name="create_vote_form" action="{% url 'vote:create_vote' id_voting=voting.id %}" method="post" novalidate>
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-6">
                            <button type="submit" id="yes_button" name="form_vote" class="btn btn-success btn-block mt-4" value="yes" >
                                Oui
                            </button>
                        </div>
                        <div class="col-6">
                            <button type="submit" name="form_vote" class="btn btn-danger btn-block mt-4" value="no">
                                Non
                            </button>
                        </div>
                    </div>
                </form>
                <div class="row">
                    <div class="col-12">
                        <a href="{% url 'vote:read_voting' id_voting=voting.id %}" role="button">
                            <button type="button" class="text-secondary btn btn-block btn-light border border-secondary mt-5">
                                Retour
                            </button>
                        </a>
                    </div>
                </div>
            </div>
            <!-- /.login-card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
</div>
<!-- /.login-page -->
{% endblock %}

vote/templates/vote/create_voting.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Votation - 
                    <span class="text-primary font-weight-bold font-italic">
                        Créer
                    </span>
                </h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-vote-yea mr-1"></i>
                Votation
            </h3>
        </div>
        <!-- /.card-body-->
        <!-- Table . 2nd card-body-->
        <div class="card-body">
            <form id="create_voting_form" action="{% url 'vote:create_voting'%}" method="post">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group mb-3">
                    {{ field.label }}
                    {{ field }}
                    {% for error in field.errors %}
                        {% if error %}
                            <p class="text-danger"> {{ error }}</p>
                        {% endif %}
                    {% endfor %}
                </div>
                {% endfor %}
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
        <!-- /end card body -->
        <div class="card-footer bg-white clearfix">
            <div class="row">
                <div class="col-sm-6 mb-2"></div>
                <div class="col-sm-3 mb-2">
                    <a href="{% url 'vote:collectivity_votings'%}" role="button">
                        <button type="button"
                            class="text-secondary btn btn-block btn-light border border-secondary">Retour</button>
                    </a>
                </div>
                <div class="col-sm-3 mb-2">
                    <button type="submit" id="create_voting_button" form="create_voting_form" class="btn btn-block btn-success">Créer</button>
                </div>
            </div>
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
{% endblock %}

vote/templates/vote/delete_voting.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class=" login-page">
    <div class="login-box ">
        <div class="login-logo">
            <a href="../../index2.html"><b>sel-</b>E</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Supprimer la votation</p>
                <p class="font-weight-bold"> "{{voting.question}}"</p>
                <form id="delete_vote_form" action="{% url 'vote:delete_voting' id_voting=voting.id %}" method="post" novalidate>
                    {% csrf_token %}
                </form>
                <div class="row">
                    <div class="col-6">
                        <a href="{{request.META.HTTP_REFERER}}" role="button">
                            <button type="button" class="text-secondary btn btn-block btn-light border border-secondary mt-4">
                                Retour
                            </button>
                        </a>
                    </div>
                    <div class="col-6">
                        <button type="submit" form="delete_vote_form" class="btn btn-danger btn-block mt-4" value="no">
                            Supprimer
                        </button>
                    </div>
                </div>
            </div>
            <!-- /.login-card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
</div>
<!-- /.login-page -->
{% endblock %}

vote/templates/vote/votings.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        {% include 'information/messages.html' %}
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Votations - <span class="text-primary font-weight-bold font-italic">
                        {{ user.collectivity.name }} ({{ user.collectivity.postal_code }})</span>
                </h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- Main row -->
        <div class="row">
            <!-- right col -->
            <!-- one col (We are only adding the ID to make the widgets sortable)-->
            <section class="col">
                <!-- Last poposals cards -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-vote-yea mr-1"></i>
                            Votations
                        </h3>
                    </div>
                    <div class="card-body mt-3 mb-1">
                        <!-- Form -->
                        <form id="collectivity_votings_form" action="{% url 'vote:collectivity_votings'%}" method="post" novalidate>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="row">
                                        <div class="col-md-7">
                                            {{form.search_input.label}}
                                            {{form.search_input}}
                                            {% for error in form.search_input.errors %}
                                                {% if error %}
                                                    <p class="text-danger"> {{ error }}</p>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        <div class="col-md-3">
                                            <button type="submit" name="cvf_search_button" value="yes"
                                                class="text-dark btn btn-block btn-light border border-secondary btn-sm mt-4">Rechercher</button>
                                        </div>
                                        <div class="col-md-2">
                                            <button type="submit" name="cvf_clear_button" value="yes"
                                                class="text-secondary font-italic btn btn-block btn-light border border-light btn-sm mt-4">Effacer</button>
                                        </div>
                                    </div>
                                    <div class="row">
                                        {% if form.non_field_errors %}
                                            {% for error in form.non_field_errors %}
                                            <p class="text-danger">{{ error }}</p>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body-->
                    <!-- Table . 2nd card-body-->
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm table-borderless">
                                <thead class="">
                                    <tr>
                                        <th>#</th>
                                        <th>Question</th>
                                        <th class="text-center">Date de création</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for voting in page_objects%}
                                        <tr>
                                            <td>
                                                {{voting.id}}
                                            </td>
                                            <td>
                                                {{voting.question}}
                                            </td>
                                            <td class="text-center">
                                                {{voting.creation_date}}
                                            </td>
                                            <td>
                                                <a href="{% url 'vote:read_voting' id_voting=voting.id %}" role="button">
                                                    <button type="button" id="watch_voting_button"
                                                        class=" text-primary btn btn-block btn-light border border-primary btn-sm">Regarder</button>
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'vote:delete_voting' id_voting=voting.id %}" role="button">
                                                    <button type="button" class="btn btn-block btn-danger btn-sm">Supprimer</button>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- /end card body -->

                    <div class="card-footer bg-white clearfix">
                        <div class="row mb-4 mt-4">
                            <div class="col-sm-8"></div>
                            <div class="col-sm-4">
                                <a href="{% url 'vote:create_voting' %}" role="button">
                                    <button type="button" id="go_to_create_voting_button" class="btn btn-block btn-success">Créer une votation</button>
                                </a>
                            </div>
                        </div>
                        {% include 'information/pagination.html' %}
                    </div>
                    <!-- /.card-footer-->
             </div>
                <!-- /.card -->
            </section>

        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}