chat/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from chat.views.collectivity_discussions_view import (
    CollectivityDiscussionsView
)
from chat.views.create_comment_view import CreateCommentView
from chat.views.create_discussion_view import CreateDiscussionView
from chat.views.read_discussion_view import ReadDiscussionView


app_name = 'chat'

urlpatterns = [
    path(
        'collectivity_discussions/',
        CollectivityDiscussionsView.as_view(),
        name='collectivity_discussions'
    ),
    path(
        'create_comment/<int:id_discussion>/',
        CreateCommentView.as_view(),
        name='create_comment'
    ),
    path(
        'create_discussion/',
        CreateDiscussionView.as_view(),
        name='create_discussion'
    ),
    path(
        'read_discussion/<int:id_discussion>/',
        ReadDiscussionView.as_view(),
        name='read_discussion'
    )
]

proposition/urls.py
# pylint: disable=C0103
"""Urls module
"""
from django.urls import path

from proposition.views.collectivity_propositions_view import (
    CollectivityPropositionsView
)
from proposition.views.create_proposition_view import CreatePropositionView
from proposition.views.delete_proposition_view import DeletePropositionView
from proposition.views.read_proposition_view import ReadPropositionView
from proposition.views.update_proposition_view import UpdatePropositionView

app_name = 'proposition'

urlpatterns = [
    path(
        'collectivity_propositions/',
        CollectivityPropositionsView.as_view(),
        name='collectivity_propositions'
    ),
    path(
        'create_proposition/',
        CreatePropositionView.as_view(),
        name='create_proposition'
    ),
    path(
        'delete_proposition/<int:id_proposition>/',
        DeletePropositionView.as_view(),
        name='delete_proposition'
    ),
    path(
        'read_proposition/<int:id_proposition>/',
        ReadPropositionView.as_view(),
        name='read_proposition'
    ),
    path(
        'update_proposition/<int:id_proposition>/',
        UpdatePropositionView.as_view(),
        name='update_proposition'
    ),
]

proposition/models.py
# pylint: disable=E0307,R0903
"""Proposition models module.
"""
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

from authentication.models import CustomUser
from chat.models import Discussion


class Category(models.Model):
    """Category model class.
    """

    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name


class CreatorType(models.Model):
    """CreatorType type model class.
    """

    name = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return self.name


class Domain(models.Model):
    """Domain model class.
    """
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


class Kind(models.Model):
    """Kind model class.
    """

    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name


class Rating(models.Model):
    """Rating class model
    """
    rate = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5)
        ]
    )

    def __str__(self):
        return self.rate


class Status(models.Model):
    """Status class model
    """
    name = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return self.name


class Proposition(models.Model):
    """Proposition model class.
    """

    name = models.CharField(max_length=128, null=False)
    description = models.TextField(max_length=1000, null=False)
    creation_date = models.DateTimeField(null=False)
    start_date = models.DateField(null=False)
    end_date = models.DateField(null=False)
    duration = models.PositiveIntegerField(
        null=False, default=60, validators=[MinValueValidator(1)]
    )
    proposition_category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=False,
        related_name="proposition_category"
    )
    proposition_creator = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE,
        related_name="proposition_creator", null=False
    )
    proposition_creator_type = models.ForeignKey(
        CreatorType, on_delete=models.CASCADE, null=False,
        related_name="proposition_creator_type"
    )
    proposition_domain = models.ForeignKey(
        Domain, on_delete=models.CASCADE, null=False,
        related_name="proposition_domain"
    )
    proposition_kind = models.ForeignKey(
        Kind, on_delete=models.CASCADE, null=False,
        related_name="proposition_kind"
    )
    proposition_rating = models.ForeignKey(
        Rating, on_delete=models.CASCADE, null=True,
        related_name="proposition_rating"
    )
    proposition_status = models.ForeignKey(
        Status, on_delete=models.CASCADE, null=False,
        related_name="proposition_status"
    )
    proposition_taker = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, null=True,
        related_name="proposition_taker"
    )
    proposition_discussion = models.ForeignKey(
        Discussion, on_delete=models.CASCADE, null=False,
        related_name="proposition_discussion"
    )

    class Meta:
        """Model metadata class.
        """

        constraints = [
            models.CheckConstraint(
                check=models.Q(start_date__lte=models.F('end_date')),
                name='start_data_lte_end_date'
            ),
            models.CheckConstraint(
                check=~models.Q(
                    proposition_creator=models.F('proposition_taker')
                ),
                name='creator_not_taker'
            )
        ]

proposition/forms/collectivity_propositions_form.py
"""CollectivityPropositionsForm (search form) module.
"""
from django.forms import CharField, Form, TextInput


class CollectivityPropositionsForm(Form):
    """CollectivityPropositionsForm (search form) class.
    """
    search_input = CharField(
        label='Rechercher',
        max_length=256,
        widget=TextInput(
            attrs={
                'id': 'input_search_proposition',
                'class': 'form-control form-control-sm',
                'autofocus': False,
            }
        )
    )

proposition/views/collectivity_proposition_view.py
from django.views import View
from django.shortcuts import render

from information.forms.navbar_search_form import NavbarSearchForm


class CollectivityPropositionView(View):
    """Collectivity Proposition view class.
    """

    def __init__(self):
        super().__init__()
        self.render = 'proposition/proposition.html'
        self.context = {
            'navbar_search_form': NavbarSearchForm(),
        }

    def get(self, request):
        """Home page view method on client get request.
        """
        return render(request, self.render, self.context)

proposition/views/collectivity_propositions_view.py
"""CollectivityPropositionsView module.
"""
from django.shortcuts import render

from proposition.forms.collectivity_propositions_form import (
    CollectivityPropositionsForm
)
from proposition.views.generic_proposition_view import (
    GenericPropositionView
)


class CollectivityPropositionsView(GenericPropositionView):
    """CollectivityPropositionsView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'proposition/propositions.html'
        self.context = {
            'form': CollectivityPropositionsForm(),
            'page_objects': None,
        }

    def get(self, request):
        """CollectivityPropositionsView method on client get request.
        """
        search_input = request.session.get('c_p_v_f_search_input', None)
        if search_input:
            self.context['page_objects'] = (
                self.manager.set_page_objects_context(request, search_input)
            )
            return render(request, self.view_template, self.context)
        self.context['page_objects'] = (
            self.manager.set_page_objects_context(request, False)
        )
        return render(request, self.view_template, self.context)

    def post(self, request):
        """CollectivityPropositionsView method on client post request.
        """
        if request.POST.get('cpf_search_button') == 'yes':
            form = CollectivityPropositionsForm(request.POST)
            if form.is_valid():
                search_input = form.cleaned_data['search_input']
                self.context['page_objects'] = (
                    self.manager.set_page_objects_context(
                        request, search_input
                    )
                )
                self.manager.set_session_vars(request, search_input)
            else:
                self.context['form'] = form
                self.context['page_objects'] = (
                    self.manager.set_page_objects_context(request, False)
                )
        else:
            self.context['page_objects'] = (
                self.manager.set_page_objects_context(request, False)
            )
            self.manager.set_session_vars(request, False)
        return render(request, self.view_template, self.context)

proposition/views/create_proposition_view.py
"""CreatePropositionView module.
"""
from django.contrib import messages
from django.shortcuts import redirect, render

from proposition.forms.proposition_form import PropositionForm
from proposition.views.generic_proposition_view import (
    GenericPropositionView
)


class CreatePropositionView(GenericPropositionView):
    """CreatePropositionView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'proposition/create_proposition.html'
        self.post_view_name = 'proposition:collectivity_propositions'
        self.context = {'form': PropositionForm()}

    def get(self, request):
        """CreatePropositionView method on client get request.
        """
        return render(request, self.view_template, self.context)

    def post(self, request):
        """CreatePropositionView method on client post request.
        """
        form = PropositionForm(request.POST)
        if form.is_valid():
            self.manager.proposition_creates_discussion(form, request.user)
            self.manager.create_proposition(form, request.user)
            messages.add_message(
                request, messages.SUCCESS, "Création réussie",
            )
            return redirect(self.post_view_name)
        self.context = {'form': form}
        return render(request, self.view_template, self.context)

proposition/views/delete_proposition_view.py
# pylint: disable=E1101
"""DeletePropositionView module
"""
from django.contrib import messages
from django.shortcuts import redirect, render

from proposition.models import Proposition, Status
from proposition.views.generic_proposition_view import (
    GenericPropositionView
)


class DeletePropositionView(GenericPropositionView):
    """DeletePropositionView class.
    """

    def __init__(self):
        super().__init__()
        self.view_template = 'proposition/delete_proposition.html'
        self.alternative_one_view_name = (
            'proposition:collectivity_propositions'
        )
        self.context = {
            'proposition': None
        }
        self.msg_post_success = "Suppression réussie"
        self.mgs_post_no_delete = (
            "Une proposition avec ce satut ne peut pas être supprimée"
        )
        self.msg_not_owner = (
            "Le créateur seulement peut supprimer la proposition"
        )

    def get(self, request, id_proposition):
        """DeletePropositionView method on client get request.
        """
        proposition = Proposition.objects.get(pk=id_proposition)
        if proposition.proposition_creator_id == request.user.id:
            self.context['proposition'] = proposition
            return render(request, self.view_template, self.context)
        messages.add_message(
            request, messages.ERROR, self.msg_not_owner,
        )
        return redirect(self.alternative_one_view_name)

    def post(self, request, id_proposition):
        """DeletePropositionView method on client post request.
        """
        proposition = Proposition.objects.get(pk=id_proposition)
        if proposition.proposition_creator_id == request.user.id:
            if proposition.proposition_status.name in ['Terminé', 'Annulé']:
                messages.add_message(
                    request, messages.WARNING, self.mgs_post_no_delete
                )
            elif proposition.proposition_status.name == 'Nouveau':
                proposition.delete()
                messages.add_message(
                    request, messages.SUCCESS, self.msg_post_success
                )
            else:
                status = Status.objects.get(name__exact='Annulé')
                proposition.proposition_status = status
                proposition.save()
                messages.add_message(
                    request, messages.SUCCESS, self.msg_post_success
                )
        else:
            messages.add_message(request, messages.ERROR, self.msg_not_owner)
        return redirect(self.alternative_one_view_name)

proposition/views/detailed_proposition_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.shortcuts import render

from proposition.management.engine.manager import Manager
from proposition.models.proposition import Proposition


class DetailedPropositionView(LoginRequiredMixin, View):
    """DetailedPropositionView class.
    """
    login_url = '/authentication/login/'
    redirect_field_name = None

    def __init__(self):
        super().__init__()
        self.manager = Manager()
        self.view_template = 'proposition/detailed_proposition.html'
        self.context = {
            'proposition': None,
            'proposition_operation': None,                      
        }
    
    def get(self, request, id_proposition):
        """Detailed proposition view method on client get request.
        """
        self.context['proposition'] = (
            Proposition.objects.get(pk=id_proposition)
        )
        self.context['proposition_operation'] = 'read'
        return render(request, self.view_template, self.context)

proposition/views/generic_proposition_view.py
"""GenericPropositionView module.
"""
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from proposition.management.engine.manager import Manager


class GenericPropositionView(LoginRequiredMixin, View):
    """GenericPropositionView class.
    """

    login_url = '/authentication/login/'
    redirect_field_name = None

    def __init__(self):
        super().__init__()
        self.manager = Manager()

proposition/views/member_proposition_view.py
from django.views import View
from django.shortcuts import render

from information.forms.navbar_search_form import NavbarSearchForm


class MemberPropositionView(View):
    """Member Proposition view class.
    """

    def __init__(self):
        super().__init__()
        self.render = 'proposition/proposition.html'
        self.context = {
            'navbar_search_form': NavbarSearchForm(),
        }

    def get(self, request):
        """Home page view method on client get request.
        """
        return render(request, self.render, self.context)

proposition/views/read_proposition_view.py
"""ReadPropositionView module.
"""
from django.shortcuts import redirect, render

from chat.forms.comment_form import CommentForm
from proposition.views.generic_proposition_view import (
    GenericPropositionView
)


class ReadPropositionView(GenericPropositionView):
    """ReadPropositionView class.
    """

    def __init__(self):
        super().__init__()

        self.view_template = 'proposition/read_proposition.html'
        self.post_view_name = 'proposition:read_proposition'
        self.context = None

    def get(self, request, id_proposition):
        """ReadPropositionView method on client get request.
        """
        self.context = self.manager.set_read_proposition_view_context(
            request, id_proposition
        )
        return render(request, self.view_template, self.context)

    def post(self, request, id_proposition):
        """ReadPropositionView method on client post request.
        """
        form = CommentForm(request.POST)
        if form.is_valid():
            self.manager.create_comment(form, request.user, id_proposition)
            return redirect(self.post_view_name, id_proposition)
        self.context = {'form': form}
        return render(
            request, self.view_template, self.context
        )

proposition/views/update_proposition_view.py
"""UpdatePropositionView module.
"""
from django.contrib import messages
from django.shortcuts import redirect

from proposition.views.generic_proposition_view import (
    GenericPropositionView
)


class UpdatePropositionView(GenericPropositionView):
    """UpdatePropositionView class.
    """

    def __init__(self):
        super().__init__()
        self.post_view_name = 'proposition:collectivity_propositions'
        self.msg_post_success = "Le statut de la proposition a été mis-à-jour"

    def post(self, request, id_proposition):
        """UpdatePropositionView method on client get request.
        """
        self.manager.set_proposition_status(request, id_proposition)
        messages.add_message(
            request, messages.SUCCESS, self.msg_post_success
        )
        return redirect(self.post_view_name)

proposition/templates/proposition/create_proposition.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Proposition - 
                    <span class="text-primary font-weight-bold font-italic">
                        Créer
                    </span>
                </h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-tag mr-1"></i>
                Proposition
            </h3>
        </div>
        <!-- /.card-body-->
        <!-- Table . 2nd card-body-->
        <div class="card-body">
            <form id="create_proposition_form" action="{% url 'proposition:create_proposition'%}" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group mb-3">
                    {{ field.label }}
                    {{ field }}
                    {% for error in field.errors %}
                        {% if error %}
                            <p class="text-danger"> {{ error }}</p>
                        {% endif %}
                    {% endfor %}
                </div>
                {% endfor %}
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
        <!-- /end card body -->
        <div class="card-footer bg-white clearfix">
            <div class="row">
                <div class="col-sm-6 mb-2"></div>
                <div class="col-sm-3 mb-2">
                    <a href="{% url 'proposition:collectivity_propositions'%}" role="button">
                        <button type="button"
                            class="text-secondary btn btn-block btn-light border border-secondary">Retour</button>
                    </a>
                </div>
                <div class="col-sm-3 mb-2">
                    <button type="submit" id="create_proposition_button" form="create_proposition_form" class="btn btn-block btn-success">Créer</button>
                </div>
            </div>
        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->
</section>
<!-- /.content -->
{% endblock %}

proposition/templates/proposition/delete_proposition.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class=" login-page">
    <div class="login-box ">
        <div class="login-logo">
            <a href="../../index2.html"><b>sel-</b>E</a>
        </div>
        <!-- /.login-logo -->
        <div class="card">
            <div class="card-body login-card-body">
                <p class="login-box-msg">Supprimer la proposition</p>
                <p class="font-weight-bold text-center"> "{{proposition.name}}"</p>
                <form id="delete_proposition_form" action="{% url 'proposition:delete_proposition' id_proposition=proposition.id %}" method="post" novalidate>
                    {% csrf_token %}
                </form>
                <div class="row">
                    <div class="col-6">
                        <a href="{{request.META.HTTP_REFERER}}" role="button">
                            <button type="button" class="text-secondary btn btn-block btn-light border border-secondary mt-4">
                                Retour
                            </button>
                        </a>
                    </div>
                    <div class="col-6">
                        <button type="submit" form="delete_proposition_form" class="btn btn-danger btn-block mt-4" value="no">
                            Supprimer
                        </button>
                    </div>
                </div>
            </div>
            <!-- /.login-card-body -->
        </div>
        <!-- /.card -->
    </div>
    <!-- /.login-box -->
</div>
<!-- /.login-page -->
{% endblock %}

proposition/templates/proposition/propositions.html
{% extends 'information/base.html' %}
{% block content %}
{% load static %}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        {% include 'information/messages.html' %}
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Proposition - <span class="text-primary font-weight-bold font-italic">
                        {{ user.collectivity.name }} ({{ user.collectivity.postal_code }})</span>
                </h1>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <!-- Main row -->
        <div class="row">
            <!-- right col -->
            <!-- one col (We are only adding the ID to make the widgets sortable)-->
            <section class="col">
                <!-- Last poposals cards -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            <i class="fas fa-tags mr-1"></i>
                            Propositions
                        </h3>
                    </div>
                    <div class="card-body mt-3 mb-1">
                        <!-- Form -->
                        <form id="collectivity_propositions_form" name="collectivity_propositions_form" action="{% url 'proposition:collectivity_propositions'%}" method="post" novalidate>
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-10 offset-md-1">
                                    <div class="row">
                                        <div class="col-md-7">
                                            {{form.search_input.label}}
                                            {{form.search_input}}
                                            {% for error in form.search_input.errors %}
                                                {% if error %}
                                                    <p class="text-danger"> {{ error }}</p>
                                                {% endif %}
                                            {% endfor %}
                                        </div>
                                        <div class="col-md-3">
                                            <button type="submit" id="search_proposition_button" name="cpf_search_button" value="yes"
                                                class="text-dark btn btn-block btn-light border border-secondary btn-sm mt-4">Rechercher</button>
                                        </div>
                                        <div class="col-md-2">
                                            <button type="submit" name="cpf_clear_button" value="yes"
                                                class="text-secondary font-italic btn btn-block btn-light border border-light btn-sm mt-4">Effacer</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- /.card-body-->
                    <!-- Table . 2nd card-body-->
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-sm table-borderless">
                                <thead class="">
                                    <tr>
                                        <th class="text-center">#</th>
                                        <th class="text-center">Nom</th>
                                        <th class="text-center">Type</th>
                                        <th class="text-center">Temps de travail</th>
                                        <th class="text-center bg-light">Statut</th>
                                        <th class="text-center">Début</th>
                                        <th class="text-center">Fin</th>
                                        <th class="text-center">Créateur</th>
                                        <th class="text-center">Preneur</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for proposition in page_objects%}
                                        <tr>
                                            <td class="text-center">
                                                {{proposition.id}}
                                            </td>
                                            <td class="text-center">
                                                {{proposition.name}}
                                            </td>
                                            <td class="text-center">
                                                {{proposition.proposition_kind}}
                                            </td>
                                            <td class="text-center">
                                                {{proposition.duration}}
                                            </td>
                                            <td class="text-center font-italic bg-light">
                                                {{proposition.proposition_status}}
                                            </td>
                                            <td class="text-center">
                                                {{proposition.start_date}}
                                            </td class="text-center">
                                            <td class="text-center">
                                                {{proposition.end_date}}
                                            </td class="text-center">
                                            <td class="text-center">
                                                {{proposition.proposition_creator.user_name}}
                                            </td>
                                            <td class="text-center">
                                                {{proposition.proposition_taker.user_name}}
                                            </td>
                                            <td>
                                                <a href="{% url 'proposition:read_proposition' id_proposition=proposition.id %}" role="button">
                                                    <button type="button" id="watch_proposition_button"
                                                        class=" text-primary btn btn-block btn-light border border-primary btn-sm">Regarder</button>
                                                </a>
                                            </td>
                                            <td>
                                                <a href="{% url 'proposition:delete_proposition' id_proposition=proposition.id %}" role="button">
                                                    <button type="button" class="btn btn-block btn-danger btn-sm">Supprimer</button>
                                                </a>
                                            </td>
                                        </tr>
                                    {% endfor%}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- /end card body -->

                    <div class="card-footer bg-white clearfix">
                        <div class="row mb-4 mt-4">
                            <div class="col-sm-8"></div>
                            <div class="col-sm-4">
                                <a href="{% url 'proposition:create_proposition'%}" role="button">
                                    <button type="button" id="go_to_create_proposition_button" class="btn btn-block btn-success">Créer une proposition</button>
                                </a>
                            </div>
                        </div>
                        {% include 'information/pagination.html' %}
                    </div>
                    <!-- /.card-footer-->
             </div>
                <!-- /.card -->
            </section>

        </div>
        <!-- /.row (main row) -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
{% endblock %}